version: '2'

services:

  wordpress:
    image: local/wordpress:4.7
    volumes:
       - ./wpdata:/var/www/html
       - ./etc/php5/apache2:/etc/php5/apache2
    ports:
      - ${WP_PORT}:80
    environment:
      WORDPRESS_DB_PASSWORD: ${DB_PWD}

  mysql:
    image: mariadb
    volumes:
      - ./mdbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PWD}
